import streamlit as st
import pandas as pd
import io


def render_export_section(df: pd.DataFrame, base_name: str = "datavyn_export"):
    st.markdown('<hr class="dv-divider">', unsafe_allow_html=True)
    st.markdown('<div class="dv-section-title" style="font-size:1rem;">📥 Export Data</div>', unsafe_allow_html=True)
    st.markdown('<div class="dv-section-sub">DOWNLOAD IN MULTIPLE FORMATS</div>', unsafe_allow_html=True)

    c1, c2, c3, c4 = st.columns(4)

    # CSV
    with c1:
        csv_buf = df.to_csv(index=False).encode("utf-8")
        st.download_button(
            "⬇️ CSV",
            data=csv_buf,
            file_name=f"{base_name}.csv",
            mime="text/csv",
            key=f"dl_csv_{base_name}",
            width='stretch'
        )

    # JSON
    with c2:
        json_buf = df.to_json(orient="records", indent=2).encode("utf-8")
        st.download_button(
            "⬇️ JSON",
            data=json_buf,
            file_name=f"{base_name}.json",
            mime="application/json",
            key=f"dl_json_{base_name}",
            width='stretch'
        )

    # Excel
    with c3:
        excel_buf = io.BytesIO()
        with pd.ExcelWriter(excel_buf, engine="openpyxl") as writer:
            df.to_excel(writer, index=False, sheet_name="Data")
        excel_buf.seek(0)
        st.download_button(
            "⬇️ Excel",
            data=excel_buf.getvalue(),
            file_name=f"{base_name}.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            key=f"dl_xlsx_{base_name}",
            width='stretch'
        )

    # PDF Summary
    with c4:
        if st.button("📄 PDF Summary", key=f"gen_pdf_{base_name}", width='stretch'):
            with st.spinner("Building PDF..."):
                try:
                    pdf_bytes = generate_data_pdf(df, base_name)
                    st.session_state[f"pdf_ready_{base_name}"] = pdf_bytes
                except Exception as e:
                    st.error(f"PDF error: {e}")

    if st.session_state.get(f"pdf_ready_{base_name}"):
        st.download_button(
            "⬇️ Download PDF Summary",
            data=st.session_state[f"pdf_ready_{base_name}"],
            file_name=f"{base_name}_summary.pdf",
            mime="application/pdf",
            key=f"dl_pdf_{base_name}"
        )


def generate_data_pdf(df: pd.DataFrame, title: str) -> bytes:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    import numpy as np

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.8*inch, bottomMargin=0.8*inch,
                            leftMargin=0.8*inch, rightMargin=0.8*inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("T", parent=styles["Title"], fontSize=18,
        textColor=colors.HexColor("#1e293b"), spaceAfter=4)
    sub_style = ParagraphStyle("S", parent=styles["Normal"], fontSize=8,
        textColor=colors.HexColor("#94a3b8"), spaceAfter=16)
    heading_style = ParagraphStyle("H", parent=styles["Heading2"], fontSize=12,
        textColor=colors.HexColor("#7c3aed"), spaceBefore=16, spaceAfter=8)
    body_style = ParagraphStyle("B", parent=styles["Normal"], fontSize=9,
        textColor=colors.HexColor("#334155"), leading=14)

    VIOLET = colors.HexColor("#7c3aed")
    LIGHT = colors.HexColor("#f8fafc")
    BORDER = colors.HexColor("#e2e8f0")

    story = []
    story.append(Paragraph(f"DataVyn Labs — Data Report: {title}", title_style))
    story.append(Paragraph(f"Rows: {len(df):,}  |  Columns: {len(df.columns)}  |  Generated by DataVyn Labs", sub_style))
    story.append(HRFlowable(width="100%", thickness=1, color=VIOLET))
    story.append(Spacer(1, 12))

    # ── Overview table
    story.append(Paragraph("Dataset Overview", heading_style))
    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    cat_cols = df.select_dtypes(include=["object"]).columns.tolist()

    overview = [
        ["Metric", "Value"],
        ["Total Rows", f"{len(df):,}"],
        ["Total Columns", str(len(df.columns))],
        ["Numeric Columns", str(len(num_cols))],
        ["Categorical Columns", str(len(cat_cols))],
        ["Missing Values", f"{df.isnull().sum().sum():,}"],
        ["Duplicate Rows", f"{df.duplicated().sum():,}"],
        ["Memory (approx)", f"{df.memory_usage(deep=True).sum() / 1024:.1f} KB"],
    ]
    tbl = Table(overview, colWidths=[3.2*inch, 3.2*inch])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), VIOLET),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [LIGHT, colors.white]),
        ("GRID", (0,0), (-1,-1), 0.5, BORDER),
        ("LEFTPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING", (0,0), (-1,-1), 5),
        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 16))

    # ── Column summary
    story.append(Paragraph("Column Details", heading_style))
    col_data = [["Column", "Type", "Missing", "Unique", "Sample Value"]]
    for col in df.columns[:20]:  # Limit to first 20
        sample = str(df[col].dropna().iloc[0])[:30] if len(df[col].dropna()) > 0 else "—"
        col_data.append([col[:25], str(df[col].dtype), str(df[col].isnull().sum()),
                          str(df[col].nunique()), sample])
    col_tbl = Table(col_data, colWidths=[1.8*inch, 0.9*inch, 0.8*inch, 0.8*inch, 2.1*inch])
    col_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), VIOLET),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 8),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [LIGHT, colors.white]),
        ("GRID", (0,0), (-1,-1), 0.5, BORDER),
        ("LEFTPADDING", (0,0), (-1,-1), 5),
        ("TOPPADDING", (0,0), (-1,-1), 4),
        ("BOTTOMPADDING", (0,0), (-1,-1), 4),
    ]))
    story.append(col_tbl)
    story.append(Spacer(1, 16))

    # ── Numeric stats
    if num_cols:
        story.append(Paragraph("Numeric Statistics", heading_style))
        desc = df[num_cols[:8]].describe().round(3)
        stat_rows = [["Stat"] + [c[:14] for c in desc.columns.tolist()]]
        for idx in desc.index:
            row = [str(idx)] + [str(v) for v in desc.loc[idx].values]
            stat_rows.append(row)

        col_w = [0.8*inch] + [max(0.7*inch, 5.6*inch / len(desc.columns))] * len(desc.columns)
        stat_tbl = Table(stat_rows, colWidths=col_w)
        stat_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), VIOLET),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("BACKGROUND", (0,1), (0,-1), colors.HexColor("#f1f5f9")),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTNAME", (0,1), (0,-1), "Helvetica-Bold"),
            ("FONTSIZE", (0,0), (-1,-1), 8),
            ("ROWBACKGROUNDS", (1,1), (-1,-1), [LIGHT, colors.white]),
            ("GRID", (0,0), (-1,-1), 0.5, BORDER),
            ("LEFTPADDING", (0,0), (-1,-1), 5),
            ("TOPPADDING", (0,0), (-1,-1), 4),
            ("BOTTOMPADDING", (0,0), (-1,-1), 4),
        ]))
        story.append(stat_tbl)
        story.append(Spacer(1, 16))

    # ── Footer
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Spacer(1, 6))
    story.append(Paragraph("Generated by DataVyn Labs • Automate Your Data. Illuminate Your Insights.", sub_style))

    doc.build(story)
    return buf.getvalue()
